apiVersion: v1
kind: Service

metadata: 
  name: mybackend-service-clip
spec:
  type: ClusterIP
  ports: 
    - targetPort: 5005
      port: 5005

  selector:
    app: my-backend
    type: backend