apiVersion: apps/v1
kind: Deployment

metadata:
  name: my-frontend-deployment
  labels:
    app: my-frontend
    type: frontend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: my-frontend
        type: frontend
    spec:
      containers:
        - name: my-frontend-container
          image: drax122/my-frontend
  replicas: 3
  selector: 
    matchLabels:
      type: frontend
      