apiVersion: v1
kind: Service

metadata: 
  name: myfrontend-service-clip
spec:
  type: ClusterIP
  ports: 
    - targetPort: 80
      port: 80

  selector:
    app: my-frontend
    type: frontend